apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-{{ .Values.deployment.color }}
  namespace: production

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: flask-app

  template:

    metadata:

      labels:
        app: flask-app
        version: {{ .Values.deployment.color }}

    spec:

      serviceAccountName: flask-sa

      containers:

      - name: flask-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 5000

        envFrom:

        - configMapRef:
            name: flask-config

        - secretRef:
            name: flask-secret

        resources:
{{ toYaml .Values.resources | indent 10 }}

        readinessProbe:

          httpGet:

            path: /health

            port: 5000

          initialDelaySeconds: 10

          periodSeconds: 5

        livenessProbe:

          httpGet:

            path: /health

            port: 5000

          initialDelaySeconds: 30

          periodSeconds: 10
